<div class="jumbotron">
    <h2>Vous etes sur <span class="text-success">Gestion des Users</span></h2>
    <p>    </p>
</div>
<div class="row">
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Nom</th>
            <th scope="col">Prenoms</th>
            <th scope="col">E-mail</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
                <tr class="table-active">
                    <th>1</th>
                    <td>AAAAAA</td>
                    <td>BBBBBBBB</td>
                    <td>CCCCCCCCCC</td>
                    <td><a href="#" class="label label-primary">Details</a></td>
                    <td><a href="#" class="label label-default">Modifier</a></td>
                    <td><a href="#" class="label label-danger">Supprimer</a></td>
                </tr>
                <tr >
                    <th>2</th>
                    <td>AAAAAA</td>
                    <td>BBBBBBBB</td>
                    <td>CCCCCCCCCC</td>
                    <td><a href="#" class="label label-primary">Details</a></td>
                    <td><a href="#" class="label label-default">Modifier</a></td>
                    <td><a href="#" class="label label-danger">Supprimer</a></td>
                </tr>
        </tbody>
    </table>
</div>